name: Library Management CI

on:
  
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Display Python Version
        run: python --version

      - name: Verify Repository
        run: |
          echo "Repository checked successfully!"

      - name: Lint README.md
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: README.md

      - name: Check requirements.txt exists
        run: bash scripts/check_requirements.sh